# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180109_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 8, 29, 12, 836833, tzinfo=utc)),
        ),
    ]
