# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180110_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 2, 47, 36, 487855, tzinfo=utc)),
        ),
    ]
